---
    - name: Set OpenStack packages for Ubuntu
      set_fact:
        openstack_packages_ubuntu:
          - python3-openstackclient
          - mariadb-server
          - rabbitmq-server
          - memcached
          - etcd

    - name: Update package cache for Ubuntu
      apt:
        update_cache: yes

    - name: Install and configure NTP for Ubuntu
      package:
        name: ntp
        state: present


